name: careppo
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.1+2

environment:
  sdk: ^3.9.2

dependencies:
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  http: ^1.6.0
  intl: ^0.20.2
  provider: ^6.1.5+1
  syncfusion_flutter_datepicker: ^31.2.10
  table_calendar: ^3.2.0
  url_launcher: ^6.3.2
  shared_preferences: ^2.5.3
  package_info_plus: ^9.0.0

dev_dependencies:
  flutter_launcher_icons: ^0.14.4
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/icon.png"
  adaptive_icon_background: "#A20505"
  adaptive_icon_foreground: "assets/icons/icon.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/images/cars/

  fonts:
    - family: LandRover
      fonts:
        - asset: assets/fonts/LandRover-Bold.otf
          weight: 700
    
    - family: DINNext
      fonts:
        - asset: assets/fonts/din-next-lt-w23-regular.ttf      

    - family: Righteous
      fonts:
        - asset: assets/fonts/Righteous-Regular.ttf
